"""initial schema

Revision ID: 807c322fadaa
Revises: 
Create Date: 2026-08-08 20:31:11.293333
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '807c322fadaa'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('antimicrobials',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('whonet_code', sa.String(length=10), nullable=True),
    sa.Column('atc_code', sa.String(length=20), nullable=True),
    sa.Column('drug_class', sa.String(length=80), nullable=False),
    sa.Column('aware_category', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_antimicrobials'))
    )
    op.create_index(op.f('ix_antimicrobials_code'), 'antimicrobials', ['code'], unique=True)
    op.create_index(op.f('ix_antimicrobials_whonet_code'), 'antimicrobials', ['whonet_code'], unique=False)
    op.create_table('audit_log',
    sa.Column('seq', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_ip', postgresql.INET(), nullable=True),
    sa.Column('target_type', sa.String(length=60), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('seq', name=op.f('pk_audit_log')),
    sa.UniqueConstraint('entry_hash', name=op.f('uq_audit_log_entry_hash'))
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index('ix_audit_log_action_time', 'audit_log', ['action', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_occurred_at'), 'audit_log', ['occurred_at'], unique=False)
    op.create_index('ix_audit_log_target', 'audit_log', ['target_type', 'target_id'], unique=False)
    op.create_index(op.f('ix_audit_log_target_id'), 'audit_log', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_log_target_type'), 'audit_log', ['target_type'], unique=False)
    op.create_table('intrinsic_resistance',
    sa.Column('organism_group', sa.String(length=120), nullable=False),
    sa.Column('agent_code', sa.String(length=10), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('breakpoint_set_version', sa.String(length=60), nullable=True),
    sa.Column('verified_locally', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intrinsic_resistance')),
    sa.UniqueConstraint('organism_group', 'agent_code', 'breakpoint_set_version', name='uq_intrinsic')
    )
    op.create_index(op.f('ix_intrinsic_resistance_breakpoint_set_version'), 'intrinsic_resistance', ['breakpoint_set_version'], unique=False)
    op.create_table('login_attempts',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('source_ip', postgresql.INET(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_attempts'))
    )
    op.create_index(op.f('ix_login_attempts_attempted_at'), 'login_attempts', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_email'), 'login_attempts', ['email'], unique=False)
    op.create_index('ix_login_attempts_email_time', 'login_attempts', ['email', 'attempted_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_source_ip'), 'login_attempts', ['source_ip'], unique=False)
    op.create_table('organisms',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('scientific_name', sa.String(length=200), nullable=False),
    sa.Column('common_name', sa.String(length=200), nullable=True),
    sa.Column('gram_stain', sa.String(length=20), nullable=True),
    sa.Column('groups', sa.ARRAY(sa.String(length=120)), nullable=False),
    sa.Column('glass_pathogen_code', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organisms'))
    )
    op.create_index(op.f('ix_organisms_code'), 'organisms', ['code'], unique=True)
    op.create_index(op.f('ix_organisms_glass_pathogen_code'), 'organisms', ['glass_pathogen_code'], unique=False)
    op.create_table('patients',
    sa.Column('pseudonym', sa.String(length=64), nullable=False),
    sa.Column('identifier_type', sa.String(length=30), nullable=False),
    sa.Column('mrn_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('name_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('date_of_birth_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('age_group', sa.String(length=20), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients'))
    )
    op.create_index(op.f('ix_patients_pseudonym'), 'patients', ['pseudonym'], unique=True)
    op.create_table('qc_ranges',
    sa.Column('breakpoint_set_version', sa.String(length=60), nullable=False),
    sa.Column('strain_designation', sa.String(length=40), nullable=False),
    sa.Column('agent_code', sa.String(length=10), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('disk_content', sa.String(length=20), nullable=True),
    sa.Column('mic_min', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('mic_max', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('zone_min_mm', sa.Integer(), nullable=True),
    sa.Column('zone_max_mm', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('mic_min IS NULL OR mic_max IS NULL OR mic_min <= mic_max', name=op.f('ck_qc_ranges_qc_mic_range_ordered')),
    sa.CheckConstraint('zone_min_mm IS NULL OR zone_max_mm IS NULL OR zone_min_mm <= zone_max_mm', name=op.f('ck_qc_ranges_qc_zone_range_ordered')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qc_ranges')),
    sa.UniqueConstraint('breakpoint_set_version', 'strain_designation', 'agent_code', 'method', name='uq_qc_range')
    )
    op.create_index(op.f('ix_qc_ranges_breakpoint_set_version'), 'qc_ranges', ['breakpoint_set_version'], unique=False)
    op.create_table('qc_strains',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('designation', sa.String(length=40), nullable=False),
    sa.Column('organism_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qc_strains')),
    sa.UniqueConstraint('code', name=op.f('uq_qc_strains_code'))
    )
    op.create_index(op.f('ix_qc_strains_designation'), 'qc_strains', ['designation'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('roles', sa.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('laboratory_code', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_laboratory_code'), 'users', ['laboratory_code'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('previous_token_hashes', sa.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=100), nullable=True),
    sa.Column('mfa_satisfied', sa.Boolean(), nullable=False),
    sa.Column('created_ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions')),
    sa.UniqueConstraint('refresh_token_hash', name=op.f('uq_auth_sessions_refresh_token_hash'))
    )
    op.create_index('ix_auth_sessions_user_active', 'auth_sessions', ['user_id', 'revoked_at'], unique=False)
    op.create_table('breakpoint_sets',
    sa.Column('version', sa.String(length=60), nullable=False),
    sa.Column('source_edition', sa.String(length=200), nullable=False),
    sa.Column('standard_body', sa.String(length=20), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_by', sa.UUID(), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_checksum', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activated_by'], ['users.id'], name=op.f('fk_breakpoint_sets_activated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_breakpoint_sets'))
    )
    op.create_index(op.f('ix_breakpoint_sets_version'), 'breakpoint_sets', ['version'], unique=True)
    op.create_table('qc_results',
    sa.Column('laboratory_code', sa.String(length=50), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('performed_by', sa.UUID(), nullable=True),
    sa.Column('strain_designation', sa.String(length=40), nullable=False),
    sa.Column('agent_code', sa.String(length=10), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('mic_operator', sa.String(length=2), nullable=True),
    sa.Column('mic_value', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('zone_diameter_mm', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('expected_range', sa.String(length=60), nullable=True),
    sa.Column('breakpoint_set_version', sa.String(length=60), nullable=True),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('corrective_action_by', sa.UUID(), nullable=True),
    sa.Column('corrective_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("outcome IN ('in_range','out_of_range','not_evaluable')", name=op.f('ck_qc_results_qc_outcome_valid')),
    sa.ForeignKeyConstraint(['corrective_action_by'], ['users.id'], name=op.f('fk_qc_results_corrective_action_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], name=op.f('fk_qc_results_performed_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qc_results'))
    )
    op.create_index(op.f('ix_qc_results_agent_code'), 'qc_results', ['agent_code'], unique=False)
    op.create_index('ix_qc_results_agent_time', 'qc_results', ['laboratory_code', 'agent_code', 'performed_at'], unique=False)
    op.create_index(op.f('ix_qc_results_laboratory_code'), 'qc_results', ['laboratory_code'], unique=False)
    op.create_index(op.f('ix_qc_results_performed_at'), 'qc_results', ['performed_at'], unique=False)
    op.create_table('report_exports',
    sa.Column('exported_by', sa.UUID(), nullable=True),
    sa.Column('exported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('content_checksum', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['exported_by'], ['users.id'], name=op.f('fk_report_exports_exported_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_exports'))
    )
    op.create_table('specimens',
    sa.Column('accession_number', sa.String(length=40), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('laboratory_code', sa.String(length=50), nullable=False),
    sa.Column('specimen_type', sa.String(length=50), nullable=False),
    sa.Column('body_site', sa.String(length=80), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('patient_origin', sa.String(length=20), nullable=True),
    sa.Column('ward', sa.String(length=80), nullable=True),
    sa.Column('infection_origin', sa.String(length=30), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_specimens_patient_id_patients'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_specimens')),
    sa.UniqueConstraint('laboratory_code', 'accession_number', name='uq_specimen_accession')
    )
    op.create_index(op.f('ix_specimens_accession_number'), 'specimens', ['accession_number'], unique=False)
    op.create_index('ix_specimens_collected', 'specimens', ['collected_at'], unique=False)
    op.create_index(op.f('ix_specimens_laboratory_code'), 'specimens', ['laboratory_code'], unique=False)
    op.create_index(op.f('ix_specimens_specimen_type'), 'specimens', ['specimen_type'], unique=False)
    op.create_table('user_invitations',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('roles', sa.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('fk_user_invitations_invited_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_invitations')),
    sa.UniqueConstraint('email', 'token_hash', name='uq_invitation'),
    sa.UniqueConstraint('token_hash', name=op.f('uq_user_invitations_token_hash'))
    )
    op.create_table('breakpoints',
    sa.Column('breakpoint_set_id', sa.UUID(), nullable=False),
    sa.Column('standard', sa.String(length=20), nullable=False),
    sa.Column('table_reference', sa.String(length=40), nullable=True),
    sa.Column('organism_group', sa.String(length=120), nullable=False),
    sa.Column('agent_code', sa.String(length=10), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('disk_content', sa.String(length=20), nullable=True),
    sa.Column('site', sa.String(length=40), nullable=True),
    sa.Column('route', sa.String(length=20), nullable=True),
    sa.Column('dosage_note', sa.Text(), nullable=True),
    sa.Column('mic_susceptible_max', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('mic_sdd_min', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('mic_sdd_max', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('mic_intermediate_min', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('mic_intermediate_max', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('mic_resistant_min', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('disk_susceptible_min', sa.Integer(), nullable=True),
    sa.Column('disk_sdd_min', sa.Integer(), nullable=True),
    sa.Column('disk_sdd_max', sa.Integer(), nullable=True),
    sa.Column('disk_intermediate_min', sa.Integer(), nullable=True),
    sa.Column('disk_intermediate_max', sa.Integer(), nullable=True),
    sa.Column('disk_resistant_max', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(length=2), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("method IN ('MIC','DISK','GRADIENT')", name=op.f('ck_breakpoints_method_valid')),
    sa.CheckConstraint('disk_susceptible_min IS NULL OR disk_resistant_max IS NULL OR disk_susceptible_min > disk_resistant_max', name=op.f('ck_breakpoints_disk_bounds_ordered')),
    sa.CheckConstraint('mic_susceptible_max IS NULL OR mic_resistant_min IS NULL OR mic_susceptible_max < mic_resistant_min', name=op.f('ck_breakpoints_mic_bounds_ordered')),
    sa.ForeignKeyConstraint(['breakpoint_set_id'], ['breakpoint_sets.id'], name=op.f('fk_breakpoints_breakpoint_set_id_breakpoint_sets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_breakpoints')),
    sa.UniqueConstraint('breakpoint_set_id', 'organism_group', 'agent_code', 'method', 'site', 'route', name='uq_breakpoint_scope')
    )
    op.create_index('ix_breakpoints_lookup', 'breakpoints', ['breakpoint_set_id', 'organism_group', 'agent_code'], unique=False)
    op.create_table('isolates',
    sa.Column('specimen_id', sa.UUID(), nullable=False),
    sa.Column('organism_id', sa.UUID(), nullable=False),
    sa.Column('isolate_number', sa.Integer(), nullable=False),
    sa.Column('identification_method', sa.String(length=60), nullable=True),
    sa.Column('infection_site', sa.String(length=40), nullable=True),
    sa.Column('is_first_isolate', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organism_id'], ['organisms.id'], name=op.f('fk_isolates_organism_id_organisms'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['specimen_id'], ['specimens.id'], name=op.f('fk_isolates_specimen_id_specimens'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_isolates')),
    sa.UniqueConstraint('specimen_id', 'organism_id', 'isolate_number', name='uq_isolate')
    )
    op.create_table('ast_results',
    sa.Column('isolate_id', sa.UUID(), nullable=False),
    sa.Column('agent_code', sa.String(length=10), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('mic_operator', sa.String(length=2), nullable=True),
    sa.Column('mic_value', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('zone_diameter_mm', sa.Integer(), nullable=True),
    sa.Column('disk_content', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=4), nullable=True),
    sa.Column('breakpoint_set_version', sa.String(length=60), nullable=True),
    sa.Column('breakpoint_table_reference', sa.String(length=40), nullable=True),
    sa.Column('interpretation_reason', sa.String(length=60), nullable=True),
    sa.Column('tier', sa.String(length=2), nullable=True),
    sa.Column('applied_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('comments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overridden_category', sa.String(length=4), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('overridden_by', sa.UUID(), nullable=True),
    sa.Column('overridden_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('suppressed', sa.Boolean(), nullable=False),
    sa.Column('suppression_reason', sa.String(length=120), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_by', sa.UUID(), nullable=True),
    sa.Column('tested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(method = 'DISK' AND zone_diameter_mm IS NOT NULL) OR (method IN ('MIC','GRADIENT') AND mic_value IS NOT NULL)", name=op.f('ck_ast_results_measurement_matches_method')),
    sa.CheckConstraint("category IS NULL OR category IN ('S','SDD','I','R','NS','NI')", name=op.f('ck_ast_results_category_valid')),
    sa.CheckConstraint('overridden_category IS NULL OR override_reason IS NOT NULL', name=op.f('ck_ast_results_override_requires_reason')),
    sa.ForeignKeyConstraint(['isolate_id'], ['isolates.id'], name=op.f('fk_ast_results_isolate_id_isolates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['overridden_by'], ['users.id'], name=op.f('fk_ast_results_overridden_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['released_by'], ['users.id'], name=op.f('fk_ast_results_released_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ast_results')),
    sa.UniqueConstraint('isolate_id', 'agent_code', 'method', name='uq_ast_result')
    )
    op.create_index('ix_ast_isolate_agent', 'ast_results', ['isolate_id', 'agent_code'], unique=False)
    op.create_index(op.f('ix_ast_results_agent_code'), 'ast_results', ['agent_code'], unique=False)
    op.create_index(op.f('ix_ast_results_breakpoint_set_version'), 'ast_results', ['breakpoint_set_version'], unique=False)
    op.create_index(op.f('ix_ast_results_category'), 'ast_results', ['category'], unique=False)
    op.create_table('interpretation_history',
    sa.Column('ast_result_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=4), nullable=True),
    sa.Column('breakpoint_set_version', sa.String(length=60), nullable=True),
    sa.Column('interpreted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interpreted_by', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=60), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ast_result_id'], ['ast_results.id'], name=op.f('fk_interpretation_history_ast_result_id_ast_results'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interpretation_history'))
    )
    op.create_index('ix_interp_history_result', 'interpretation_history', ['ast_result_id', 'interpreted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_interp_history_result', table_name='interpretation_history')
    op.drop_table('interpretation_history')
    op.drop_index(op.f('ix_ast_results_category'), table_name='ast_results')
    op.drop_index(op.f('ix_ast_results_breakpoint_set_version'), table_name='ast_results')
    op.drop_index(op.f('ix_ast_results_agent_code'), table_name='ast_results')
    op.drop_index('ix_ast_isolate_agent', table_name='ast_results')
    op.drop_table('ast_results')
    op.drop_table('isolates')
    op.drop_index('ix_breakpoints_lookup', table_name='breakpoints')
    op.drop_table('breakpoints')
    op.drop_table('user_invitations')
    op.drop_index(op.f('ix_specimens_specimen_type'), table_name='specimens')
    op.drop_index(op.f('ix_specimens_laboratory_code'), table_name='specimens')
    op.drop_index('ix_specimens_collected', table_name='specimens')
    op.drop_index(op.f('ix_specimens_accession_number'), table_name='specimens')
    op.drop_table('specimens')
    op.drop_table('report_exports')
    op.drop_index(op.f('ix_qc_results_performed_at'), table_name='qc_results')
    op.drop_index(op.f('ix_qc_results_laboratory_code'), table_name='qc_results')
    op.drop_index('ix_qc_results_agent_time', table_name='qc_results')
    op.drop_index(op.f('ix_qc_results_agent_code'), table_name='qc_results')
    op.drop_table('qc_results')
    op.drop_index(op.f('ix_breakpoint_sets_version'), table_name='breakpoint_sets')
    op.drop_table('breakpoint_sets')
    op.drop_index('ix_auth_sessions_user_active', table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_users_laboratory_code'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_qc_strains_designation'), table_name='qc_strains')
    op.drop_table('qc_strains')
    op.drop_index(op.f('ix_qc_ranges_breakpoint_set_version'), table_name='qc_ranges')
    op.drop_table('qc_ranges')
    op.drop_index(op.f('ix_patients_pseudonym'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_organisms_glass_pathogen_code'), table_name='organisms')
    op.drop_index(op.f('ix_organisms_code'), table_name='organisms')
    op.drop_table('organisms')
    op.drop_index(op.f('ix_login_attempts_source_ip'), table_name='login_attempts')
    op.drop_index('ix_login_attempts_email_time', table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_email'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_attempted_at'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index(op.f('ix_intrinsic_resistance_breakpoint_set_version'), table_name='intrinsic_resistance')
    op.drop_table('intrinsic_resistance')
    op.drop_index(op.f('ix_audit_log_target_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_target_id'), table_name='audit_log')
    op.drop_index('ix_audit_log_target', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_occurred_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_index('ix_audit_log_action_time', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_antimicrobials_whonet_code'), table_name='antimicrobials')
    op.drop_index(op.f('ix_antimicrobials_code'), table_name='antimicrobials')
    op.drop_table('antimicrobials')
    # ### end Alembic commands ###
