"""initial schema

Revision ID: 81c454dd741d
Revises: 
Create Date: 2026-08-08 19:07:30.297504+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '81c454dd741d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_antibiotic',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('antimicrobial_class', sa.Enum('penicillin', 'beta_lactam_inhibitor_combination', 'cephalosporin', 'carbapenem', 'monobactam', 'aminoglycoside', 'fluoroquinolone', 'macrolide', 'lincosamide', 'tetracycline', 'glycopeptide', 'oxazolidinone', 'folate_pathway_inhibitor', 'nitrofuran', 'polymyxin', 'phenicol', 'azole', 'echinocandin', 'polyene', 'pyrimidine_analogue', 'other', name='antimicrobial_class'), nullable=False),
    sa.Column('target_kingdom', sa.Enum('bacteria', 'fungi', name='antibiotic_target_kingdom'), nullable=False),
    sa.Column('who_aware_category', sa.String(length=16), nullable=True),
    sa.Column('atc_code', sa.String(length=16), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_canonical_antibiotic')),
    sa.UniqueConstraint('code', name=op.f('uq_canonical_antibiotic_code'))
    )
    op.create_table('canonical_organism',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('kingdom', sa.Enum('bacteria', 'fungi', name='organism_kingdom'), nullable=False),
    sa.Column('genus', sa.String(length=128), nullable=True),
    sa.Column('family', sa.String(length=128), nullable=True),
    sa.Column('gram_stain', sa.String(length=16), nullable=True),
    sa.Column('is_enterobacterales', sa.Boolean(), nullable=False),
    sa.Column('is_organism_of_special_importance', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_canonical_organism')),
    sa.UniqueConstraint('code', name=op.f('uq_canonical_organism_code'))
    )
    op.create_table('canonical_specimen_type',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('infection_site', sa.String(length=64), nullable=False),
    sa.Column('is_sterile_site', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_canonical_specimen_type')),
    sa.UniqueConstraint('code', name=op.f('uq_canonical_specimen_type_code'))
    )
    op.create_table('regional_block',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('governing_body', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('activated_at', sa.Date(), nullable=True),
    sa.Column('whonet_config_standard', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regional_block')),
    sa.UniqueConstraint('code', name=op.f('uq_regional_block_code'))
    )
    op.create_table('district',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('regional_block_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['regional_block_id'], ['regional_block.id'], name=op.f('fk_district_regional_block_id_regional_block')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_district')),
    sa.UniqueConstraint('regional_block_id', 'name', name=op.f('uq_district_regional_block_id_name'))
    )
    op.create_index(op.f('ix_district_regional_block_id'), 'district', ['regional_block_id'], unique=False)
    op.create_table('methodology_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('component', sa.Enum('antibiogram', 'deduplication', 'suppression', 'qc_rules', 'emerging_signal_trigger', 'phenotype_flags', 'ast_breakpoints', 'analytics_engine', 'linkage_hash', name='methodology_component'), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('regional_block_id', sa.UUID(), nullable=True),
    sa.Column('is_provisional', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(length=256), nullable=True),
    sa.Column('approved_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['regional_block_id'], ['regional_block.id'], name=op.f('fk_methodology_version_regional_block_id_regional_block')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_methodology_version')),
    sa.UniqueConstraint('component', 'version', name=op.f('uq_methodology_version_component_version'))
    )
    op.create_index('ix_methodology_effective', 'methodology_version', ['component', 'effective_from'], unique=False)
    op.create_table('facility',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Enum('pending', 'under_verification', 'active', 'suspended', 'inactive', 'retired', name='facility_status'), nullable=False),
    sa.Column('whonet_config_version', sa.String(length=64), nullable=True),
    sa.Column('qc_status', sa.Enum('satisfactory', 'unsatisfactory', 'not_submitted', 'expired', name='qc_status'), nullable=False),
    sa.Column('qc_valid_until', sa.Date(), nullable=True),
    sa.Column('eqa_status', sa.Enum('satisfactory', 'unsatisfactory', 'not_submitted', 'expired', name='eqa_status'), nullable=False),
    sa.Column('eqa_valid_until', sa.Date(), nullable=True),
    sa.Column('upload_schedule', sa.Enum('weekly', 'fortnightly', 'monthly', 'custom', name='upload_schedule'), nullable=False),
    sa.Column('upload_interval_days', sa.Integer(), nullable=True),
    sa.Column('last_accepted_upload_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mou_signed_on', sa.Date(), nullable=True),
    sa.Column('mou_reference', sa.String(length=128), nullable=True),
    sa.Column('enrollment_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], name=op.f('fk_facility_district_id_district')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facility')),
    sa.UniqueConstraint('code', name=op.f('uq_facility_code'))
    )
    op.create_index(op.f('ix_facility_district_id'), 'facility', ['district_id'], unique=False)
    op.create_table('app_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=256), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('laboratory_staff', 'facility_administrator', 'data_steward', 'regional_amr_administrator', 'clinician', 'auditor', 'system_administrator', name='user_role'), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=True),
    sa.Column('regional_block_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], name=op.f('fk_app_user_facility_id_facility')),
    sa.ForeignKeyConstraint(['regional_block_id'], ['regional_block.id'], name=op.f('fk_app_user_regional_block_id_regional_block')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user')),
    sa.UniqueConstraint('email', name=op.f('uq_app_user_email'))
    )
    op.create_index(op.f('ix_app_user_facility_id'), 'app_user', ['facility_id'], unique=False)
    op.create_index(op.f('ix_app_user_regional_block_id'), 'app_user', ['regional_block_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_label', sa.String(length=256), nullable=False),
    sa.Column('actor_role', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['app_user.id'], name=op.f('fk_audit_log_actor_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_actor_time', 'audit_log', ['actor_id', 'occurred_at'], unique=False)
    op.create_index('ix_audit_entity', 'audit_log', ['entity', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_occurred_at'), 'audit_log', ['occurred_at'], unique=False)
    op.create_table('emerging_signal',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('regional_block_id', sa.UUID(), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=True),
    sa.Column('facility_id', sa.UUID(), nullable=True),
    sa.Column('canonical_organism_id', sa.UUID(), nullable=False),
    sa.Column('canonical_antibiotic_id', sa.UUID(), nullable=False),
    sa.Column('detected_on', sa.Date(), nullable=False),
    sa.Column('baseline_start', sa.Date(), nullable=False),
    sa.Column('baseline_end', sa.Date(), nullable=False),
    sa.Column('baseline_susceptible_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('baseline_n', sa.Integer(), nullable=False),
    sa.Column('current_start', sa.Date(), nullable=False),
    sa.Column('current_end', sa.Date(), nullable=False),
    sa.Column('current_susceptible_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('current_n', sa.Integer(), nullable=False),
    sa.Column('change_percentage_points', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('methodology_version_id', sa.UUID(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by_id', sa.UUID(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['app_user.id'], name=op.f('fk_emerging_signal_acknowledged_by_id_app_user')),
    sa.ForeignKeyConstraint(['canonical_antibiotic_id'], ['canonical_antibiotic.id'], name=op.f('fk_emerging_signal_canonical_antibiotic_id_canonical_antibiotic')),
    sa.ForeignKeyConstraint(['canonical_organism_id'], ['canonical_organism.id'], name=op.f('fk_emerging_signal_canonical_organism_id_canonical_organism')),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], name=op.f('fk_emerging_signal_district_id_district')),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], name=op.f('fk_emerging_signal_facility_id_facility')),
    sa.ForeignKeyConstraint(['methodology_version_id'], ['methodology_version.id'], name=op.f('fk_emerging_signal_methodology_version_id_methodology_version')),
    sa.ForeignKeyConstraint(['regional_block_id'], ['regional_block.id'], name=op.f('fk_emerging_signal_regional_block_id_regional_block')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emerging_signal'))
    )
    op.create_index('ix_signal_scope', 'emerging_signal', ['regional_block_id', 'detected_on'], unique=False)
    op.create_table('eqa_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=False),
    sa.Column('panel', sa.String(length=128), nullable=False),
    sa.Column('assessment_date', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('performance', sa.Enum('satisfactory', 'unsatisfactory', 'not_submitted', 'expired', name='eqa_performance'), nullable=False),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('submitted_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], name=op.f('fk_eqa_record_facility_id_facility')),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['app_user.id'], name=op.f('fk_eqa_record_submitted_by_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eqa_record'))
    )
    op.create_index(op.f('ix_eqa_record_facility_id'), 'eqa_record', ['facility_id'], unique=False)
    op.create_table('facility_code_mapping',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('organism', 'antibiotic', 'specimen_type', name='dictionary_entity_type'), nullable=False),
    sa.Column('local_code', sa.String(length=64), nullable=False),
    sa.Column('local_label', sa.String(length=256), nullable=True),
    sa.Column('canonical_code', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('proposed', 'approved', 'rejected', name='mapping_status'), nullable=False),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('observed_record_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], name=op.f('fk_facility_code_mapping_facility_id_facility')),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['app_user.id'], name=op.f('fk_facility_code_mapping_reviewed_by_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facility_code_mapping')),
    sa.UniqueConstraint('facility_id', 'entity_type', 'local_code', name=op.f('uq_facility_code_mapping_facility_id_entity_type_local_code'))
    )
    op.create_index(op.f('ix_facility_code_mapping_facility_id'), 'facility_code_mapping', ['facility_id'], unique=False)
    op.create_table('upload_batch',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('submitted_by_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('accepted_isolate_count', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('payload_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('staged', 'qc_hold', 'accepted', 'quarantined', 'retracted', 'rejected', name='batch_status'), nullable=False),
    sa.Column('uploader_version', sa.String(length=32), nullable=False),
    sa.Column('whonet_config_version', sa.String(length=64), nullable=True),
    sa.Column('ast_breakpoint_standard', sa.String(length=64), nullable=True),
    sa.Column('coverage_start', sa.Date(), nullable=True),
    sa.Column('coverage_end', sa.Date(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by_id', sa.UUID(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_id'], ['app_user.id'], name=op.f('fk_upload_batch_decided_by_id_app_user')),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], name=op.f('fk_upload_batch_facility_id_facility')),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['app_user.id'], name=op.f('fk_upload_batch_submitted_by_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upload_batch'))
    )
    op.create_index(op.f('ix_upload_batch_facility_id'), 'upload_batch', ['facility_id'], unique=False)
    op.create_table('analytics_refresh',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('regional_block_id', sa.UUID(), nullable=False),
    sa.Column('triggered_by_batch_id', sa.UUID(), nullable=True),
    sa.Column('trigger_reason', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('signals_detected', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['regional_block_id'], ['regional_block.id'], name=op.f('fk_analytics_refresh_regional_block_id_regional_block')),
    sa.ForeignKeyConstraint(['triggered_by_batch_id'], ['upload_batch.id'], name=op.f('fk_analytics_refresh_triggered_by_batch_id_upload_batch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_refresh'))
    )
    op.create_index(op.f('ix_analytics_refresh_regional_block_id'), 'analytics_refresh', ['regional_block_id'], unique=False)
    op.create_table('isolate',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('upload_batch_id', sa.UUID(), nullable=False),
    sa.Column('specimen_date', sa.Date(), nullable=False),
    sa.Column('specimen_iso_year', sa.Integer(), nullable=False),
    sa.Column('specimen_iso_week', sa.Integer(), nullable=False),
    sa.Column('age_band', sa.Enum('<5', '5-14', '15-44', '45-64', '65+', 'unknown', name='age_band'), nullable=False),
    sa.Column('age_exact_years', sa.Integer(), nullable=True),
    sa.Column('sex', sa.Enum('male', 'female', 'unknown', name='sex'), nullable=False),
    sa.Column('care_setting', sa.Enum('IPD', 'OPD', 'unknown', name='care_setting'), nullable=False),
    sa.Column('canonical_specimen_type_id', sa.UUID(), nullable=False),
    sa.Column('canonical_organism_id', sa.UUID(), nullable=False),
    sa.Column('organism_kingdom', sa.Enum('bacteria', 'fungi', name='isolate_organism_kingdom'), nullable=False),
    sa.Column('patient_linkage_key', sa.LargeBinary(length=32), nullable=False),
    sa.Column('source_record_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_organism_id'], ['canonical_organism.id'], name=op.f('fk_isolate_canonical_organism_id_canonical_organism')),
    sa.ForeignKeyConstraint(['canonical_specimen_type_id'], ['canonical_specimen_type.id'], name=op.f('fk_isolate_canonical_specimen_type_id_canonical_specimen_type')),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], name=op.f('fk_isolate_facility_id_facility')),
    sa.ForeignKeyConstraint(['upload_batch_id'], ['upload_batch.id'], name=op.f('fk_isolate_upload_batch_id_upload_batch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_isolate')),
    sa.UniqueConstraint('facility_id', 'source_record_hash', name='isolate_source_record')
    )
    op.create_index('ix_isolate_analytics', 'isolate', ['facility_id', 'canonical_organism_id', 'specimen_date'], unique=False)
    op.create_index(op.f('ix_isolate_canonical_organism_id'), 'isolate', ['canonical_organism_id'], unique=False)
    op.create_index(op.f('ix_isolate_canonical_specimen_type_id'), 'isolate', ['canonical_specimen_type_id'], unique=False)
    op.create_index('ix_isolate_dedup', 'isolate', ['facility_id', 'patient_linkage_key', 'canonical_organism_id'], unique=False)
    op.create_index(op.f('ix_isolate_facility_id'), 'isolate', ['facility_id'], unique=False)
    op.create_index(op.f('ix_isolate_upload_batch_id'), 'isolate', ['upload_batch_id'], unique=False)
    op.create_table('qc_attestation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('satisfactory', 'unsatisfactory', 'not_submitted', 'expired', name='qc_attestation_status'), nullable=False),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_by_id', sa.UUID(), nullable=True),
    sa.Column('upload_batch_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], name=op.f('fk_qc_attestation_facility_id_facility')),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['app_user.id'], name=op.f('fk_qc_attestation_submitted_by_id_app_user')),
    sa.ForeignKeyConstraint(['upload_batch_id'], ['upload_batch.id'], name=op.f('fk_qc_attestation_upload_batch_id_upload_batch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qc_attestation')),
    sa.UniqueConstraint('facility_id', 'period_start', name=op.f('uq_qc_attestation_facility_id_period_start'))
    )
    op.create_index(op.f('ix_qc_attestation_facility_id'), 'qc_attestation', ['facility_id'], unique=False)
    op.create_table('upload_qc_finding',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('upload_batch_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'error', name='qc_finding_severity'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('affected_record_count', sa.Integer(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_id', sa.UUID(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['app_user.id'], name=op.f('fk_upload_qc_finding_resolved_by_id_app_user')),
    sa.ForeignKeyConstraint(['upload_batch_id'], ['upload_batch.id'], name=op.f('fk_upload_qc_finding_upload_batch_id_upload_batch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upload_qc_finding'))
    )
    op.create_index(op.f('ix_upload_qc_finding_upload_batch_id'), 'upload_qc_finding', ['upload_batch_id'], unique=False)
    op.create_table('ast_result',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('isolate_id', sa.UUID(), nullable=False),
    sa.Column('canonical_antibiotic_id', sa.UUID(), nullable=False),
    sa.Column('result', sa.Enum('S', 'I', 'R', 'SDD', 'NS', 'NI', name='sir_result'), nullable=False),
    sa.Column('mic_value', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('mic_operator', sa.String(length=2), nullable=True),
    sa.Column('zone_diameter_mm', sa.Integer(), nullable=True),
    sa.Column('test_method', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_antibiotic_id'], ['canonical_antibiotic.id'], name=op.f('fk_ast_result_canonical_antibiotic_id_canonical_antibiotic')),
    sa.ForeignKeyConstraint(['isolate_id'], ['isolate.id'], name=op.f('fk_ast_result_isolate_id_isolate')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ast_result')),
    sa.UniqueConstraint('isolate_id', 'canonical_antibiotic_id', name=op.f('uq_ast_result_isolate_id_canonical_antibiotic_id'))
    )
    op.create_index(op.f('ix_ast_result_canonical_antibiotic_id'), 'ast_result', ['canonical_antibiotic_id'], unique=False)
    op.create_index(op.f('ix_ast_result_isolate_id'), 'ast_result', ['isolate_id'], unique=False)
    op.create_table('phenotype_flag',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('isolate_id', sa.UUID(), nullable=False),
    sa.Column('flag_code', sa.String(length=48), nullable=False),
    sa.Column('methodology_version_id', sa.UUID(), nullable=False),
    sa.Column('basis', sa.Text(), nullable=False),
    sa.Column('is_screening_level', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['isolate_id'], ['isolate.id'], name=op.f('fk_phenotype_flag_isolate_id_isolate')),
    sa.ForeignKeyConstraint(['methodology_version_id'], ['methodology_version.id'], name=op.f('fk_phenotype_flag_methodology_version_id_methodology_version')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phenotype_flag')),
    sa.UniqueConstraint('isolate_id', 'flag_code', name=op.f('uq_phenotype_flag_isolate_id_flag_code'))
    )
    op.create_index(op.f('ix_phenotype_flag_isolate_id'), 'phenotype_flag', ['isolate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phenotype_flag_isolate_id'), table_name='phenotype_flag')
    op.drop_table('phenotype_flag')
    op.drop_index(op.f('ix_ast_result_isolate_id'), table_name='ast_result')
    op.drop_index(op.f('ix_ast_result_canonical_antibiotic_id'), table_name='ast_result')
    op.drop_table('ast_result')
    op.drop_index(op.f('ix_upload_qc_finding_upload_batch_id'), table_name='upload_qc_finding')
    op.drop_table('upload_qc_finding')
    op.drop_index(op.f('ix_qc_attestation_facility_id'), table_name='qc_attestation')
    op.drop_table('qc_attestation')
    op.drop_index(op.f('ix_isolate_upload_batch_id'), table_name='isolate')
    op.drop_index(op.f('ix_isolate_facility_id'), table_name='isolate')
    op.drop_index('ix_isolate_dedup', table_name='isolate')
    op.drop_index(op.f('ix_isolate_canonical_specimen_type_id'), table_name='isolate')
    op.drop_index(op.f('ix_isolate_canonical_organism_id'), table_name='isolate')
    op.drop_index('ix_isolate_analytics', table_name='isolate')
    op.drop_table('isolate')
    op.drop_index(op.f('ix_analytics_refresh_regional_block_id'), table_name='analytics_refresh')
    op.drop_table('analytics_refresh')
    op.drop_index(op.f('ix_upload_batch_facility_id'), table_name='upload_batch')
    op.drop_table('upload_batch')
    op.drop_index(op.f('ix_facility_code_mapping_facility_id'), table_name='facility_code_mapping')
    op.drop_table('facility_code_mapping')
    op.drop_index(op.f('ix_eqa_record_facility_id'), table_name='eqa_record')
    op.drop_table('eqa_record')
    op.drop_index('ix_signal_scope', table_name='emerging_signal')
    op.drop_table('emerging_signal')
    op.drop_index(op.f('ix_audit_log_occurred_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_index('ix_audit_entity', table_name='audit_log')
    op.drop_index('ix_audit_actor_time', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_app_user_regional_block_id'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_facility_id'), table_name='app_user')
    op.drop_table('app_user')
    op.drop_index(op.f('ix_facility_district_id'), table_name='facility')
    op.drop_table('facility')
    op.drop_index('ix_methodology_effective', table_name='methodology_version')
    op.drop_table('methodology_version')
    op.drop_index(op.f('ix_district_regional_block_id'), table_name='district')
    op.drop_table('district')
    op.drop_table('regional_block')
    op.drop_table('canonical_specimen_type')
    op.drop_table('canonical_organism')
    op.drop_table('canonical_antibiotic')
    # ### end Alembic commands ###
